[package]
name = "nats_bench"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = {"version" = "0.42.0", features = ["default"]}
bytes = "1.10.1"
futures = "0.3.31"
tokio = { version = "1.46.1", features = ["full", "rt-multi-thread"] }
